artifact_location: file:///C:/Users/ihernan6/root/MLDS/MLDSUNAL/tdsp_template/XGboost.v1/0
creation_time: 1753653140006
experiment_id: '0'
last_update_time: 1753653140006
lifecycle_stage: active
name: Default
